### PR TITLE
implement logic for signal.setPublic(...)

### PR DESCRIPTION
**Pull request by denise-opendaq**
- [x] New feature (non-breaking change which adds functionality)

# Checklist:

- [ ] Pull request title reflects its content
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

# Description:

### CODE REVIEW

**Review by JakaMohorkoDS — APPROVED** [review]
Lgtm for the OPC UA side of things. Should wait for @NikolaiShipilov for the streaming implementation.

Also as far as I can tell, we are still missing the StreamingLT (WebsocketStreamingServer) implementation?

**Comment by NikolaiShipilov** [comment]
Is it possible that the data signal is public and its domain signal is not public? If so, then a non-public domain signal should still be published in streaming, at least in the native one, since domain packets are streamed explicitly within the native streaming.

**Review by NikolaiShipilov — APPROVED** [review]

**Comment by JakaMohorkoDS** [comment]
> ~@JakaMohorkoDS Is it possible that the data signal is public and its domain signal is not public? If so, then a non-public domain signal should still be published in streaming, at least in the native one, since domain packets are streamed explicitly within the native streaming.~
> 
> > Also as far as I can tell, we are still missing the StreamingLT (WebsocketStreamingServer) implementation?
> 
> That one could be placed [here](https://github.com/openDAQ/openDAQ/blob/main/shared/libraries/websocket_streaming/src/streaming_server.cpp#L138)
> 
> @JakaMohorkoDS Since private signals are not published over OpcUa shouldn't these also be excluded in Native config protocol ?

Good point, though I'm not 100% certain at which point that should be implemented. Maybe on the deserialization side where the signal would not be attached to the tree if it's not public?

**Comment by nilsRoettgerAtBB** [comment]
Can this be merged now? I am waiting for it, that it goes into main :-)

**Review by JakaMohorkoDS — APPROVED** [review]

**Pull request merged**
