### PR TITLE
Inject openDAQ version from a single file

### PR DESCRIPTION
**Pull request by aljazfrancic**
# Type of change:

- [x] New feature (non-breaking change which adds functionality)
- [x] This change requires a documentation update

# Checklist:

- [x] Pull request title reflects its content
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] New and existing unit tests pass locally with my changes

# Description:
Inject openDAQ version string into multiple files throughout CI/repo so only one file needs to be edited during version bump.

### CODE REVIEW

**Comment by aljazfrancic** [comment]
Need to figure out `openDAQ.Net.csproj`, however I have a few ideas on how to approach that.

**Comment by aljazfrancic** [comment]
Also not sure if `opendaq.github.io` will require an update... (?)

**Comment by aljazfrancic** [comment]
> Need to figure out `openDAQ.Net.csproj`, however I have a few ideas on how to approach that.

Same for `openDAQDemo.Net.csproj`

**Review by Daniel-BB — APPROVED** [review]
Looks good from my point of view

**Pull request merged**
